name: Release
on:
  push:
    tags: [ '*' ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Build
      run: gem build *.gemspec
    - name: Push on Rubygems
      run: gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_API_KEY}}
